// Splices SERIES data (default: tools/waypoints-raw.json) and ROUTE_GEOM (tools/route-geom.json)
// back into index.html, replacing the existing `var SERIES = [...]` block and inserting a
// `var ROUTE_GEOM = {...}` block immediately before it.
//   node tools/apply-to-html.mjs [--input=waypoints-raw.json]
import fs from 'node:fs';

const inputArg = process.argv.find((a) => a.startsWith('--input='));
const inputFile = inputArg ? inputArg.slice('--input='.length) : 'waypoints-raw.json';

const htmlPath = new URL('../index.html', import.meta.url);
let html = fs.readFileSync(htmlPath, 'utf8');

const fixed = JSON.parse(fs.readFileSync(new URL('./' + inputFile, import.meta.url), 'utf8'));
const geom = JSON.parse(fs.readFileSync(new URL('./route-geom.json', import.meta.url), 'utf8'));

function jsStringLiteral(s) {
  return "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}
function pointLiteral(p) {
  return '[' + p[0] + ',' + p[1] + ']';
}
function courseLiteral(c) {
  const r = c.r.map(pointLiteral).join(',');
  return `{ n:${jsStringLiteral(c.n)}, name:${jsStringLiteral(c.name)}, c:${pointLiteral(c.c)}, r:[${r}] }`;
}
function seriesLiteral(s) {
  const courses = s.courses.map(courseLiteral).join(',\n        ');
  return `    {\n      id: ${jsStringLiteral(s.id)}, name: ${jsStringLiteral(s.name)}, color: ${jsStringLiteral(s.color)},\n      courses: [\n        ${courses}\n      ]\n    }`;
}
const seriesText = 'var SERIES = [\n' + fixed.map(seriesLiteral).join(',\n') + '\n  ];';

// find existing SERIES block by bracket-matching (same approach as extract-series.mjs)
const startMarker = 'var SERIES = [';
const startIdx = html.indexOf(startMarker);
if (startIdx === -1) throw new Error('SERIES not found in index.html');
let i = startIdx + 'var SERIES = '.length, depth = 0, end = -1;
for (; i < html.length; i++) {
  const ch = html[i];
  if (ch === '[') depth++;
  else if (ch === ']') { depth--; if (depth === 0) { end = i + 1; break; } }
}
// consume trailing ';' if present
let blockEnd = end;
if (html[blockEnd] === ';') blockEnd++;

const before = html.slice(0, startIdx);
const after = html.slice(blockEnd);

// Remove any previously-inserted ROUTE_GEOM block (idempotent re-runs)
const geomBeginMarker = '/* ROUTE_GEOM:BEGIN';
const geomEndMarker = 'ROUTE_GEOM:END */';
let cleanedBefore = before;
const gStart = cleanedBefore.indexOf(geomBeginMarker);
if (gStart !== -1) {
  const gEnd = cleanedBefore.indexOf(geomEndMarker, gStart);
  if (gEnd !== -1) {
    cleanedBefore = cleanedBefore.slice(0, gStart) + cleanedBefore.slice(gEnd + geomEndMarker.length);
  }
}

const geomBlock =
  '  /* ROUTE_GEOM:BEGIN  generated by tools/build-routes.mjs — DO NOT EDIT BY HAND */\n' +
  '  var ROUTE_GEOM = ' + JSON.stringify(geom) + ';\n' +
  '  /* ROUTE_GEOM:END */\n\n  ';

html = cleanedBefore + geomBlock + seriesText + after;
fs.writeFileSync(htmlPath, html, 'utf8');
console.log('index.html updated:', fixed.reduce((a, s) => a + s.courses.length, 0), 'courses,', Object.keys(geom).length, 'geometries embedded');
